Bump version to 16.0.3 (C++17 support)
unikraft/lib-compiler-rt pull request #11
Opened 2023-05-04 10:03 UTC by andreittr

Updated lib-compiler-rt to the latest upstream version; based off earlier work from @mschlumpp & @marcrittinghaus .
Part of a patch set w/ further PRs under libcxx, libcxxabi, libunwind & lib-musl.

2023-05-04 18:23 UTC, StefanJum requested changes
Thank you @andreittr. besides the few inline comments:

* Please change the commits to match the [`unikraft`  commit format](https://unikraft.org/docs/contributing/submitting-changes/#commits). (i.e. sign-off them and add the `co-authored-by` and `sign-off` of the co-authors, add the `component/selector` to the commit message).
* Why are there so many changes to the `Makefile.uk` file? It looks like the source files are just reordered, removed from one place and added again. Is this intended (is there a specific order it follows)?

Besides that, functionally it seems to work fine, I'll keep testing.

2023-05-04 18:23 UTC, StefanJum commented on Config.uk
>  if LIBCOMPILER_RT
Is there a reason this `if` condition is still present? It doesn't seem to do anything.

2023-05-04 18:43 UTC, mschlumpp commented
> Why are there so many changes to the `Makefile.uk` file? It looks like the source files are just reordered, removed from one place and added again. Is this intended (is there a specific order it follows)?

I'm pretty sure that Marc sorted the file list lexicographically.

2023-05-04 18:44 UTC, StefanJum commented
> I'm pretty sure that Marc sorted the file list lexicographically.

Yeah that makes sense, thanks.

2023-05-05 15:51 UTC, andreittr commented
Building libcxx v16 requires GCC >= 12 and that is a bit too restrictive a change for now.
I'm going to close this set of PRs and resubmit new ones that bump LLVM only to 14, along with the minimal necessary changes to get it working. libcxx 14 _does_ compile with GCC 11 (though not with earlier versions :( ).

2023-05-05 15:51 UTC, closed without merging